### ISSUE TITLE
Add visual regression testing

### ISSUE THREAD

**Issue by kyranjamie** [leather-wallet/mono#21]
This will be a great addition, that should be [fairly straightforward to add when we have Storybook](https://storybook.js.org/docs/react/writing-tests/visual-testing)

it'll make visual bugs like this a thing of the past

![image](https://github.com/leather-wallet/mono/assets/1618764/49abf75d-841f-49b7-a24b-b812a5c3d6d8)

**Comment by pete-watters** [comment]
> Is this the same as [leather-wallet/extension#4937](https://github.com/leather-wallet/extension/issues/4937)?

Yes, I'll merge them. We can have visual regression both in storybook but also outside of storybook using playwright
