### ISSUE TITLE
Second pass at buttons recipe

### ISSUE THREAD

**Issue by kyranjamie** [leather-wallet/mono#35]
There are a few improvements to buttons we need to make:

- Add size variants. Design system has small and medium buttons, but we only have medium
- Adjust border radii
- Ghost variant has no background colour

cc/ @mica000 @fabric-8 to suggest any other improvements needed for buttons

**Comment by fbwoolf** [comment]
I am working on this here, so I'll close this one in favor of:
https://github.com/leather-wallet/extension/issues/4418
