### ISSUE TITLE
Suggest approach to extract bitcoin logic from extension to mono

### ISSUE THREAD

**Issue by kyranjamie** [leather-wallet/mono#4]
This is an exercise in software design. We need to consider the best way to move bitcoin logic into a generic package.

Let's figure out how this package/these packages may be structured, diagramming their relation.

Related https://github.com/leather-wallet/extension/issues/4299

**Comment by pete-watters** [comment]
I think we can close this off as a duplicate of https://github.com/leather-wallet/extension/issues/4297 .

We will plan there and have a diagram: https://github.com/leather-wallet/extension/issues/4297#issuecomment-1809861163
