### ISSUE TITLE
Design tokens package

### ISSUE THREAD

**Issue by kyranjamie** [leather-wallet/mono#5]
Move design tokens to monorepo.

TBD: Do we need to tiers tokens -> panda, or can we use panda to keep tokens, even if we don't use panda when consuming?

**Comment by pete-watters** [comment]
I added this package and manually published it here https://www.npmjs.com/package/@leather-wallet/tokens

I'll make sure its consumable by the extension before closing this off. 

The basic mono repo auto publish I set up is no longer working so I will need to spend some time fixing that - https://github.com/leather-wallet/mono/issues/29

**Comment by pete-watters** [comment]
I opened a PR to consume this tokens package in the extension: https://github.com/leather-wallet/extension/pull/4602 

I just moved token object for now and kept panda specific stuff inside the `extension`.
